### ISSUE TITLE
`setup.py sdist` fails: No such file or directory: '/tmp/pip-req-build-u2lhg91r/DESCRIPTION.rst'

### ISSUE THREAD

**Issue by scruss** [sparkfun/Qwiic_AS6212_Py#1]
Raspberry Pi Zero, Raspberry Pi OS Buster, fully updated.

Attempting to fix Qwiic_py as detailed here: https://forum.sparkfun.com/viewtopic.php?f=105&t=56505&p=228898#p228898, a manual installation of this module:

    git clone https://github.com/sparkfun/Qwiic_AS6212_Py.git
    cd Qwiic_AS6212_Py/
    python3 ./setup.py sdist
    cd dist/
    sudo pip3 install sparkfun_qwiic_as6212-0.0.2.tar.gz 
    Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
    Processing ./sparkfun_qwiic_as6212-0.0.2.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-req-build-u2lhg91r/setup.py", line 44, in <module>
            with io.open(path.join(here, "DESCRIPTION.rst"), encoding="utf-8") as f:
        FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-u2lhg91r/DESCRIPTION.rst'
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-u2lhg91r/

**Comment by santaimpersonator** [comment]
Hey there, I'm going to close this issue:

- Technically, the `setup.py` method is deprecated according to the `setuptools` documentation. However, it is still being supported for now.
    - With that said, I'm not sure why you would need to rebuild this Python package. You should be able to install the package with the `pip3 install sparkfun_qwiic_as6212` command in the terminal. That will install the pre-built Python package, hosted on PyPI.
- Your issue in the forum can be tracked here: https://github.com/sparkfun/Qwiic_Py/issues/25

**Comment by scruss** [comment]
> With that said, I'm not sure why you would need to rebuild this Python package.

When I opened this issue nearly three years ago, there was no prebuilt package on PyPI. I was following the exact instructions given by SparkFun at the time, and they didn't work. Nice to know that this is “[look[ing] into the matter as soon as possible](https://forum.sparkfun.com/viewtopic.php?p=228927#p228927)” …

**Comment by santaimpersonator** [comment]
- My apologies, I meant that we usually provide a prebuilt package on PyPI, whenever we publish a release
    > With that said, I'm not sure why you would need to rebuild this Python package. You should be able to install the package with the `pip3 install sparkfun_qwiic_as6212` command in the terminal. That will install the pre-built Python package, hosted on PyPI.
    - i.e. When we initially set our GitHub repository for a Python package public
    - i.e. When we update the Python package
- In regards to this package not being available on PyPI.
    - According to the time stamps on PyPI for the [`sparkfun-qwiic-as6212` project](https://pypi.org/project/sparkfun-qwiic-as6212/), as shown in the [release history](https://pypi.org/project/sparkfun-qwiic-as6212/#history) and [available files](https://pypi.org/project/sparkfun-qwiic-as6212/#files), our prebuilt package should have been available on August 27, 2021.
        ![image](https://github.com/sparkfun/Qwiic_AS6212_Py/assets/36016723/6aa8f667-292f-419a-97cc-2a11b2005e1d)
- About the instructions we provided, are you referring to the information in the `README.md` file?
    - Looks like there may have been a copy/paste error... the `Local Installation` and `Rebuild Package` headings are missing.
        - Most users should only need to utilize the `pip` installation instructions.
        - The rest of the methods, were for manual installation (using the `setuptools` package) or for software development.
    ![image](https://github.com/sparkfun/Qwiic_AS6212_Py/assets/36016723/4c47aa28-1b1e-4cf8-984a-008794ddbe84)

**Comment by scruss** [comment]
I would have used pip/PyPI had it been available. There may have been an error that prevented it working at the time, but the system I would have been trying it on were re-imaged long ago and are lost. Just so long as it works for other people now.
